# Generated by Django 5.2.17 on 2026-08-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('making_charges_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purities', to='products.metal')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('delist', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], default='Unisex', max_length=10)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('product_model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_time', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_available', models.BooleanField(default=False)),
                ('stone_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('stone_color', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_count', models.IntegerField(blank=True, null=True)),
                ('stone_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('stone_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diamond_available', models.BooleanField(default=False)),
                ('dia_desc', models.TextField(blank=True, null=True)),
                ('dia_cent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('dia_count', models.IntegerField(blank=True, null=True)),
                ('dia_cut', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_color', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_clarity', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('beads_available', models.BooleanField(default=False)),
                ('beads_desc', models.TextField(blank=True, null=True)),
                ('beads_color', models.CharField(blank=True, max_length=100, null=True)),
                ('beads_count', models.IntegerField(blank=True, null=True)),
                ('beads_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('beads_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pearls_available', models.BooleanField(default=False)),
                ('pearls_desc', models.TextField(blank=True, null=True)),
                ('pearls_color', models.CharField(blank=True, max_length=100, null=True)),
                ('pearls_count', models.IntegerField(blank=True, null=True)),
                ('pearls_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pearls_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('search_keywords', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.metal')),
                ('metal_purity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.metalpurity')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal_purity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.metalpurity')),
            ],
            options={
                'indexes': [models.Index(fields=['effective_date', 'metal_purity'], name='products_go_effecti_7a75bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
    ]
